### ISSUE TITLE
关于extract-dialogue项目的一些问题

### ISSUE THREAD

**Issue by ayangge** [KMnO4-zx/extract-dialogue#3]
大佬您好，想请教您两个问题：
1.这个DEEPSEEK_API该怎么填。
2.要提取的小说或文本的格式有要求吗。一定要是txt格式吗，pdf或者doc等可不可以

**Comment by KMnO4-zx** [comment]
1. 创建一个.env文件，然后在里面写入即可。如下所示：
```
OPENAI_API_KEY='sk-xxxx'
OPENAI_BASE_URL='xxx' 
```
2. 目前只适配了txt格式的，你也可以写一个pdf md的解析函数即可

**Comment by ayangge** [comment]
我是新手，请问DEEPSEEK_API该怎么获取

**Comment by KMnO4-zx** [comment]
https://platform.deepseek.com/usage

注册即可

**Comment by ayangge** [comment]
感谢感谢，我试一下

**Comment by ayangge** [comment]
.env也是txt格式是吧
